csv_chunk_size: 50
max_threads: 10
max_processes: 6
aws_profile: collectionspace
aws_media_ingest_profile: shared
# Create a directory to hold your client configs, and enter the path to it
client_config_dir: fixturesdir/data
# Path to file that will hold the name of the client config you are currently
#   working on.
config_name_file: fixturesdir/current_config
bastion_user: yourusername
# The following are set by default but you can change them by uncommenting
# db_port: 5432
# db_connect_host: localhost
# Number of seconds to wait between getting new DB tunnel and attempting to
#   get database connection. Will be set by default, but can be overridden
#   by uncommenting in your config. Increase this number if this tool is
#   failing to create a database connection, but you can make the connection
#   via psql or pgAdmin with the same credentials.
# db_tunnel_connection_pause: 3
